#ifndef IDAPTIK_H
#define IDAPTIK_H

/* Auto-generated by cbindgen — do not edit by hand. Regenerate with `just ffi-header`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque owner of a [`GhostLobbySim`] run plus the persistent held-button set.
 *
 * The sim consumes one folded `TickInput` per 60 Hz frame, and held movement
 * buttons persist *across* ticks (`SetButton` presses stay down until released
 * — see how the TUI's `InputState::sample` feeds `GhostLobbySim::tick`). The
 * handle carries that held set so FFI callers speak the same per-tick
 * `Command` stream the Elixir session layer and the TUI already share, and
 * [`idaptik_core::scenario::fold`] collapses it exactly as they do.
 */
typedef struct GhostLobbyHandle GhostLobbyHandle;

/**
 * Opaque owner of a [`Network`]. Consumers hold this as an opaque pointer and
 * only touch it through the functions below.
 */
typedef struct NetworkHandle NetworkHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Build the demonstration network. The caller owns the returned pointer and
 * must release it with [`idap_network_free`].
 */
struct NetworkHandle *idap_demo_network(void);

/**
 * Free a network previously returned by this library. Passing null is a no-op.
 *
 * # Safety
 * `ptr` must be a pointer returned by this library and not already freed.
 */
void idap_network_free(struct NetworkHandle *ptr);

/**
 * Number of devices in the network. Returns 0 for a null pointer.
 *
 * # Safety
 * `ptr` must be null or a valid pointer from this library.
 */
uintptr_t idap_network_device_count(const struct NetworkHandle *ptr);

/**
 * Start a Ghost Lobby run: the bundled scenario definition, full motion, the
 * given seed and difficulty. The caller owns the returned pointer and must
 * release it with [`idap_ghost_lobby_free`].
 *
 * `difficulty` is a NUL-terminated string: `"story"`, `"standard"` or
 * `"operator"` (case-insensitive). Returns null — never panics — if
 * `difficulty` is null, not UTF-8 or not one of those three, or if the
 * bundled definition fails validation.
 *
 * The startup events (`RunStarted`, `SeedAnnounced`) are queued inside the
 * sim; the first [`idap_ghost_lobby_tick_json`] returns them ahead of its own
 * events.
 *
 * # Safety
 * `difficulty` must be null or a valid NUL-terminated C string.
 */
struct GhostLobbyHandle *idap_ghost_lobby_new(uint32_t seed, const char *difficulty);

/**
 * Advance the run by exactly one fixed 60 Hz frame and return that tick's
 * events as an owned JSON string. Free it with [`idap_string_free`].
 *
 * JSON contract (the same wire the Elixir session layer and the TUI share):
 *
 * - **In** — `commands_json` is a JSON array of `Command` values for this
 *   tick, e.g. `[{"cmd":"SetButton","button":"Right","down":true},
 *   {"cmd":"Jump"}]`, or `[]` for an idle frame. The stream is folded into one
 *   `TickInput`: `SetButton` mutates the handle's persistent held set (held
 *   buttons stay down across later ticks until released), edges and
 *   immediates apply this tick in stream order.
 * - **Out** — on success, a JSON array of the tick's `Event` values (the
 *   first tick is prefixed with the queued startup events). On a recoverable
 *   failure (null/invalid `commands_json`, or an unexpected panic in the sim,
 *   which is contained here rather than crossing the boundary) an
 *   `{"error":"..."}` object. Null only when `ptr` is null or allocation
 *   fails.
 *
 * # Safety
 * `ptr` must be null or a live pointer from [`idap_ghost_lobby_new`], not
 * freed, and not used concurrently from another thread. `commands_json` must
 * be null or a valid NUL-terminated C string.
 */
char *idap_ghost_lobby_tick_json(struct GhostLobbyHandle *ptr, const char *commands_json);

/**
 * Serialise a full, restorable `RuntimeSnapshot` of the run at the current
 * tick (format tag `idaptik-ghost-lobby-runtime-v2`) as an owned JSON string.
 * Free it with [`idap_string_free`]. Returns an `{"error":"..."}` object on a
 * recoverable failure; null only when `ptr` is null or allocation fails.
 *
 * # Safety
 * `ptr` must be null or a live pointer from [`idap_ghost_lobby_new`], not
 * freed, and not used concurrently from another thread.
 */
char *idap_ghost_lobby_snapshot_json(const struct GhostLobbyHandle *ptr);

/**
 * Free a Ghost Lobby run previously returned by [`idap_ghost_lobby_new`].
 * Passing null is a no-op.
 *
 * # Safety
 * `ptr` must be null or a pointer returned by this library and not already
 * freed.
 */
void idap_ghost_lobby_free(struct GhostLobbyHandle *ptr);

/**
 * Free a string previously returned by this library ([`idap_ghost_lobby_tick_json`],
 * [`idap_ghost_lobby_snapshot_json`]). Passing null is a no-op.
 *
 * # Safety
 * `s` must be null or a string returned by this library and not already freed.
 */
void idap_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* IDAPTIK_H */
